### ISSUE TITLE
Food Planning

### ISSUE THREAD

**Issue by amglovier** [HospitalRun/planning#3]
**Grocery Stores**
* Safeway - 1020 Johnson Ln, South Lake Tahoe, CA 96150
* Grocery Outlet Bargain Market - 2358 Lake Tahoe Blvd, South Lake Tahoe, CA 96150
* Raley's - 4000 Lake Tahoe Blvd, South Lake Tahoe, CA 96150
* Alpine Liquor -  3460 Lake Tahoe Blvd, South Lake Tahoe, CA 96150
* Dart Discount Liquors - 148 US-50, Stateline, NV 89449

**Restaurants**
* German
  * Himmel Haus - http://himmelhaustahoe.com/ (.3 miles from house)
* Sushi
  * http://www.thenakedfish.com/
* Mexican
  * Azul Latin Kitchen - http://azullatinkitchen.com/ (healthier version of Mexican food with locally grown and sourced ingredients
  * Chimayó Street Grill - http://www.chimayotahoe.com/
* Fine Dining
  * Nepheles - http://nepheles.com/ (eclectic California fare)
  * Cafe Fiore - http://www.cafefiore.com/index.html (Italien) 

**Take Out**
* Blue Dog Pizza 
  * http://bluedogpizzatahoe.com/ 
  * GF crusts available
* Vinny's
  * http://www.vinnyspizzatahoe.com/
   * New York style pizza 

**Cafe/Diner's**
  * Red Hut Cafe - http://www.redhutcafe.com/menus.html
  * Driftwood Cafe - http://www.driftwoodtahoe.com/
  * IHOP - 3730 Lake Tahoe Blvd, South Lake Tahoe, CA 96150

**Comment by jglovier** [comment]
Thanks for planning all of this @amglovier! It was a wildly successful week, and we have you to thank for taking care of all the logistics. :heart: :metal: :zap:
